### ISSUE TITLE
about use

### ISSUE THREAD

**Issue by jiangyanjavawin** [marcelteun/show-off#1]
Hello,thank you for your code,but i don't know how to use it,when i run local_off.html,it can't show off file on my web.Please help me and how to fix it.Thank you very much.

**Comment by marcelteun** [comment]
What is it you are trying to do? Which off files are you trying to load?
I have it running here:
http://tunnissen.eu/polyh/local_off.html
Can you load your off-file here?

Cheers,
Marcel  "Teun"

**Comment by jiangyanjavawin** [comment]
Thanks for your reply.My meaning is very simply.I just want to show stable off file by html Components like canvas,not like your url show is load off.Your url i have try,it work very well.Thanks very much.

**Comment by marcelteun** [comment]
The meaning of "local" in local_off.html is that a visitor can load a file that they have locally on their phone/computer. Sometimes someone sends me an off-file by e-mail and I only have my phone, then I use that page to have a look at it. 

If I understand well, then you want more to use show-off-bundle.js. that one can be generated as explained in the README file. Something like this:
http://tunnissen.eu/polyh/reg-fld-hepts/octahedral_quatrinja_star.html
Do I understand right?

If you have problems generating the bundle yourself, just use the one you find on my web-page there
https://tunnissen.eu/js/show-off-bundle.js
Last time I generated the bundle was quite some time ago (interfaces might have changed in the dependencies e.g.)

Cheers
Marcel "Teun"

**Comment by marcelteun** [comment]
Perhaps I should include a generated version of the bundle, but usually you only add the source code in a repo, not anything that is generated from the source code. I will see,..

**Comment by jiangyanjavawin** [comment]
> Perhapd I should include a generated version of the bundle, but usually you only add the source code in a repo, not anything that is generated from the source code. I will see,..

Thank you very much,I will try.

**Comment by marcelteun** [comment]
Did you succeed?

**Comment by jiangyanjavawin** [comment]
> 
> 
> Did you succeed?

not yet

**Comment by marcelteun** [comment]
Then I will leave the issue open.
Did you try? Any problems?

/MT

**Comment by jiangyanjavawin** [comment]
> 
> 
> Then I will leave the issue open.
> Did you try? Any problems?
> 
> /MT

Thank you open the issue so long,You can close it.I will try other method.
